-- create-user.sql
-- Create a MySQL user

CREATE USER 'mysql'@'192.168.1.10' IDENTIFIED BY '1234';
CREATE USER 'mysql'@'localhost' IDENTIFIED BY '1234';
CREATE DATABASE IF NOT EXISTS meditrack;
GRANT ALL PRIVILEGES ON *.* TO 'mysql'@'192.168.1.10' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'mysql'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
